urls.py
# -*- coding: utf-8 -*-

"""
Author: zqbai
Created Time: 2023/7/7 20:42
"""
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),

    path('index/book/', views.BookIndexView.as_view(), name='book_index'),
    path('index/student/', views.student_index, name='student_index'),

    path('detail/book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('detail/student/<int:pk>', views.student_detail, name="student_detail"),

    path('search/book', views.BookSearchView.as_view(), name='book_search'),
    path('search/student', views.student_search, name='student_search'),

    path('run/book/<int:book_id>/<int:student_id>', views.book_run, name='book_run'),
    path('run/student/<int:book_id>/<int:student_id>',views.stu_run, name='student_run'),

    path('index/category/', views.category_index,name='category_index'),
    path('index/school/', views.school_index, name='school_index'),
    path('index/major/', views.major_index, name='major_index'),

    path('detail/school/<int:pk>',views.school_detail,name="school_detail"),
    path('detail/major/<int:pk>', views.major_detail, name="major_detail"),
    path('detail/category/<int:pk>', views.category_detail, name="category_detail")

]

templates/books/base_file/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>zqbai的图书管理小应用</title>
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.css' %}">

</head>
<body>


    <div style="text-align: center;"><h2 class="my-4">A Tiny Book Management Application by zqbai</h2></div>

    <div class="container my-4">
    <div class="row justify-content-between align-items-center">
        <div class="col-auto">
            <h3 class="col-auto">{% block subtitle %}{% endblock %}</h3>
        </div>
        <div class="col-auto">
            <form action="{% url 'books:index' %}" method="get" class="mb-0">
                <button type="submit" class="btn btn-outline-secondary">Go back Home</button>
            </form>
        </div>
    </div>
</div>


        {% block content %}{% endblock %}


</body>
</html>

templates/books/base_file/book_list.html
<div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    {{ list_title }}
                </h4>
            </div>

            <div class="card-body small" style="height:450px;overflow-y: scroll;">
                {% if books %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-1">ID</div>
                        <div class="col-4">Name</div>
                        <div class="col-2"><a href="{% url 'books:category_index' %}" class="text-black text-decoration-none">Category</a> </div>
                        <div class="col-2"><a href="{% url 'books:school_index' %}" class="text-decoration-none text-black">Provided School</a> </div>
                        <div class="col-1">B.Times</div>
                        <div class="col-1">Quantity</div>
                        <div class="col-1">Latest B.</div>
                    </div>
                    {% for book in books %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-1"><a href="{% url 'books:book_detail' book.id %}">{{ book.id }}</a></div>
                        <div class="col-4"><a href="{% url 'books:book_detail' book.id %}" class="text-black text-decoration-none">《{{ book.name }}》</a></div>
                        <div class="col-2"><a href="{% url 'books:category_detail' book.category.id %}" class="text-decoration-none text-black">{{ book.category }}</a> </div>
                        <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis"><a href="{% url 'books:school_detail' book.offered_by.id %}" class="text-black text-decoration-none">{{ book.offered_by.name }}</a> </div>
                        <div class="col-1">{{ book.borrow_times_db }}</div>
                        <div class="col-1"> {{ book.available_quantity|stringformat:"02d" }}/{{ book.total_quantity|stringformat:"02d" }}</div>
                        <div class="col-1">{{ book.latest_borrow_date|date:"y-m-d"|default:"None"}}</div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No books are available.</p>
                {% endif %}
            </div>

        </div>
</div>

templates/books/base_file/book_search_form.html
<div class="container my-4">
    <form action="{% url 'books:book_search' %}" method="get">
        <div class="input-group">
            <input type="text" class="form-control" name="q" placeholder="Search by Book ID or Book Name" aria-label="Search" value={{ q }}>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>

templates/books/base_file/student_list.html
<div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    {{ list_title }}
                </h4>
            </div>

            <form method="GET" class="mx-2">
            <div class="row">
                <div class="col-auto"><label for="pageInput{{ page_param }}" class="mt-3">Enter page number:</label></div>
                <div class="col-2">
                    <input id="pageInput{{ page_param }}" type="number" name="{{ page_param }}" class="form-control mt-3" min="1" max="{{ pages.paginator.num_pages }}" placeholder="Page number" required style="font-size: small" value={{ page|default:None }}>
                </div>
                <input type="hidden" name="{{ other_page_param }}" value="{{ other_page }}">
                <div class="col-auto">
                <button type="submit" class="btn btn-outline-secondary mt-3" style="font-size: small">Go</button>
                </div>
                {% if pages.has_previous %}
                    <div class="col-auto ms-auto">
                        <a style="font-size: small" href="?{{ page_param }}={{ pages.previous_page_number }}&{{ other_page_param }}={{ other_page }}" class="btn btn-outline-secondary mt-3 {% if not pages.has_previous %}disabled{% endif %}">Previous Page</a>
                    </div>
                {% endif %}
{#            这里对最右的格式设置不太一样#}
            </div>
            </form>


            <div class="card-body" style="height:450px;overflow-y: scroll;">
                {% if pages %}
                    <div class="row mb-2 border-bottom fw-bold">
                        <div class="col-1">Stu_ID</div>
                        <div class="col-2">Name</div>
                        <div class="col-1">Sex</div>
                        <div class="col-2"><a href="{% url 'books:school_index' %}" class="text-decoration-none text-black">School</a></div>
                        <div class="col-2"><a href="{% url 'books:major_index' %}" class="text-black text-decoration-none">Major</a></div>
                        <div class="col-1">Grade</div>
                        <div class="col-1">B. Times</div>
                        <div class="col-1">Latest B.</div>
                        <div class="col-1">Latest R.</div>
                    </div>
                    {% for student in pages %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-1"><a href="{% url 'books:student_detail' student.id %}">{{ student.stu_id }}</a></div>
                        <div class="col-2"><a href="{% url 'books:student_detail' student.id %}" class="text-decoration-none text-black">{{ student.name }}</a></div>
                        <div class="col-1">{{ student.sex }}</div>
                        <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis"><a href="{% url 'books:school_detail' student.school.id %}" class="text-black text-decoration-none">{{ student.school.name }}</a> </div>
                        <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis"><a href="{% url 'books:major_detail' student.major.id %}" class="text-decoration-none text-black"> {{ student.major }} </a></div>
                        <div class="col-1">{{ student.grade }}</div>
                        <div class="col-1">{{ student.borrow_times}}</div>
                        <div class="col-1">{{ student.latest_borrow_date|date:"y-m-d"|default:"None"}}</div>
                        <div class="col-1">{{ student.latest_return_date|date:"y-m-d"|default:"None"}}</div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No student's data is available.</p>
                {% endif %}
            {% if pages.has_next %}
            <div class="d-flex justify-content-end">
                <a style="font-size: small" href="?{{ page_param }}={{ pages.next_page_number }}&{{ other_page_param }}={{ other_page }}" class="btn btn-outline-secondary mt-3 {% if not pages.has_next %}disabled{% endif %}">Next Page</a>
{#            Django没提供Load more功能#}
            </div>
            {% endif %}
            </div>


        </div>
</div>

templates/books/base_file/student_search_form.html
<div class="container my-4">
    <form action="{% url 'books:student_search' %}" method="get">
        <div class="input-group">
            <input type="text" class="form-control" name="q" placeholder="Search by Student ID or Student Name" aria-label="Search" value={{ q }}>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>