urls.py
# -*- coding: utf-8 -*-

"""
Author: zqbai
Created Time: 2023/7/7 20:42
"""
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),

    path('index/book/', views.BookIndexView.as_view(), name='book_index'),
    path('index/student/', views.student_index, name='student_index'),

    path('detail/book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('detail/student/<int:pk>', views.student_detail, name="student_detail"),

    path('search/book', views.BookSearchView.as_view(), name='book_search'),
    path('search/student', views.student_search, name='student_search'),

    path('run/book/<int:book_id>/<int:student_id>', views.book_run, name='book_run'),
    path('run/student/<int:book_id>/<int:student_id>',views.stu_run, name='student_run'),

    path('index/category/', views.category_index,name='category_index'),
    path('index/school/', views.school_index, name='school_index'),
    path('index/major/', views.major_index, name='major_index'),

    path('detail/school/<int:pk>',views.school_detail,name="school_detail"),
    path('detail/major/<int:pk>', views.major_detail, name="major_detail"),
    path('detail/category/<int:pk>', views.category_detail, name="category_detail")

]

templates/books/index_file/book_index.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Bookoogle it, and you will know
{% endblock %}

{% block content %}

    {% include 'books/base_file/book_search_form.html' %}

    {% include 'books/base_file/book_list.html' with books=most_borrow_list list_title="Ranked by the number of books borrowed" %}

    {% include 'books/base_file/book_list.html' with books=all_books list_title="Ranked by the id of books" %}



{% endblock content %}

templates/books/index_file/category_index.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Categorooogle
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    Category List
                </h4>
            </div>

            <div class="card-body">
                {% if categories %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-2">ID</div>
                        <div class="col-5">Category</div>
                    </div>
                    {% for category in categories %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-2">{{ category.id }}</div>
                        <div class="col-5"><a href="{% url 'books:category_detail' category.id %}" class="text-black text-decoration-none">{{ category.name }}</a></div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No Categories are available.</p>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content %}

templates/books/index_file/index.html
{% extends "books/base_file/base.html" %}

{% block content %}
    <div class="container">
        <div class="text-center mt-5">
            <div class="d-grid gap-3 col-md-6 mx-auto">
                <a href="{% url 'books:book_index' %}" class="btn btn-outline-secondary">Search By Books</a>
                <a href="{% url 'books:student_index' %}" class="btn btn-outline-primary">Search By Students</a>
                <a href="{% url 'books:school_index' %}" class="btn btn-outline-danger">Search By Schools</a>
                <a href="{% url 'books:major_index' %}" class="btn btn-outline-success">Search By Majors</a>
                <a href="{% url 'books:category_index' %}" class="btn btn-outline-warning">Search By Categories</a>

            </div>
        </div>
    </div>
{% endblock content %}

templates/books/index_file/major_index.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Majorooooogle
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    Major List
                </h4>
            </div>

            <div class="card-body">
                {% if majors %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-2">ID</div>
                        <div class="col-5">Major</div>
                    </div>
                    {% for major in majors %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-2">{{ major.id }}</div>
                        <div class="col-5"><a href="{% url 'books:major_detail' major.id %}" class="text-black text-decoration-none">{{ major.name }}</a></div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No Majors are available.</p>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content %}

templates/books/index_file/school_index.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Schoooooogle
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    School List
                </h4>
            </div>

            <div class="card-body">
                {% if schools %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-1">ID</div>
                        <div class="col-5">Name</div>
                        <div class="col-5">Location</div>
                    </div>
                    {% for school in schools %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-1">{{ school.id }}</div>
                        <div class="col-5"><a href="{% url 'books:school_detail' school.id %} " class="text-decoration-none text-black">《{{ school.name }}》</a></div>
                        <div class="col-5">{{ school.location }}</div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No School are available.</p>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content %}

templates/books/index_file/student_index.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Studenoogle it, and you will know
{% endblock %}

{% block content %}
    {% include 'books/base_file/student_search_form.html' %}

    {% include 'books/base_file/student_list.html' with page_param='page1' other_page_param='page2' page=page1 other_page=page2 pages=no_all_return_student_pages list_title="Students Who have not returned all the borrowed books" %}

    {% include 'books/base_file/student_list.html' with page_param='page2' other_page_param='page1' page=page2 other_page=page1 pages=all_return_student_ordered_by_borrow_time_pages list_title="Students ranked by the number of books they have borrowed." %}

{#我想实现两个表同时分页的功能，可能显得有些繁琐，book_index界面则没有那么繁琐#}
{#    如果有更好方法之后再修改#}

{% endblock content %}