urls.py
# -*- coding: utf-8 -*-

"""
Author: zqbai
Created Time: 2023/7/7 20:42
"""
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),

    path('index/book/', views.BookIndexView.as_view(), name='book_index'),
    path('index/student/', views.student_index, name='student_index'),

    path('detail/book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('detail/student/<int:pk>', views.student_detail, name="student_detail"),

    path('search/book', views.BookSearchView.as_view(), name='book_search'),
    path('search/student', views.student_search, name='student_search'),

    path('run/book/<int:book_id>/<int:student_id>', views.book_run, name='book_run'),
    path('run/student/<int:book_id>/<int:student_id>',views.stu_run, name='student_run'),

    path('index/category/', views.category_index,name='category_index'),
    path('index/school/', views.school_index, name='school_index'),
    path('index/major/', views.major_index, name='major_index'),

    path('detail/school/<int:pk>',views.school_detail,name="school_detail"),
    path('detail/major/<int:pk>', views.major_detail, name="major_detail"),
    path('detail/category/<int:pk>', views.category_detail, name="category_detail")

]

models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib import admin

import datetime

TIMEOUTLIMIT = timezone.now() - datetime.timedelta(days=30)


class School(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def offer_book_count(self):
        return Book.objects.filter(
            offered_by=self,
            pub_date__lte=timezone.now()
        ).count()

    def offer_total_quantity(self):
        return Book.objects.filter(
            offered_by=self,
            pub_date__lte=timezone.now()
        ).aggregate(models.Sum('total_quantity'))['total_quantity__sum']

    def borrow_quantity(self):
        return BorrowRecord.objects.filter(
            student__school=self,
            borrow_date__lte=timezone.now()
        ).count()


class Major(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def borrow_quantity(self):
        return BorrowRecord.objects.filter(
            student__major=self,
            borrow_date__lte=timezone.now()
        ).count()


class Student(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    YEAR_CHOICES = [(r, r) for r in range(1980, datetime.date.today().year + 2)]
    stu_id = models.CharField(max_length=8)
    name = models.CharField(max_length=200)
    school = models.ForeignKey(School, on_delete=models.PROTECT)
    sex = models.CharField(max_length=1, choices=GENDER_CHOICES)
    major = models.ForeignKey(Major, on_delete=models.PROTECT)
    grade = models.IntegerField(choices=YEAR_CHOICES)
    # borrow_time = models.IntegerField(default=0)  这里不跟books用同一种存储方法，这里不用冗余优化
    is_all_return_db = models.BooleanField(default=True) # 冗余优化
    borrow_times_db = models.IntegerField(default=0)  #还是用冗余优化吧，太慢了

    def __str__(self):
        return f"{self.stu_id}-{self.name}"

    def borrow_times(self):
        return BorrowRecord.objects.filter(
            student=self,
            borrow_date__lte=timezone.now()
        ).count()

    # 非冗余方法,好慢好慢，
    @property
    def return_times(self):
        borrow_records = BorrowRecord.objects.filter(
            student=self,
            borrow_date__lte=timezone.now()
        )
        return ReturnRecord.objects.filter(
            borrowrecord__in=borrow_records,
            borrowrecord__borrow_date__lte=timezone.now()
        ).count()

    def is_all_return(self):
        return self.return_times == self.borrow_times_db
    @property
    def notreturn_records(self):
        if self.is_all_return():
            return None
        else:
            borrow_records = BorrowRecord.objects.filter(
                student=self,
                borrow_date__lte=timezone.now(),
            )
            # 借走的记录
            return_records = ReturnRecord.objects.filter(
                borrowrecord__in=borrow_records,
                borrowrecord__borrow_date__lte=timezone.now()
            )
            # 归还的记录
            not_return_records = borrow_records.exclude(
                id__in=return_records.values_list('borrowrecord_id', flat=True)
            ).order_by('borrow_date')
            # 借走中未归还的记录

            return not_return_records
    def time_out_records(self):
        if self.notreturn_records():
            return self.notreturn_records().filter(
                borrow_date__lte=TIMEOUTLIMIT
            )
        else:
            return None

    def latest_borrow_date(self):
        latest_borrow_record = BorrowRecord.objects.filter(
            student=self,
            borrow_date__lte=timezone.now()
        ).order_by('-borrow_date').first()
        if latest_borrow_record:
            return latest_borrow_record.borrow_date
        else:
            return None

    def latest_return_date(self):
        latest_return_record = ReturnRecord.objects.filter(
            borrowrecord__student=self,
            borrowrecord__borrow_date__lte=timezone.now()
        ).order_by('-return_date').first()

        if latest_return_record:
            return latest_return_record.return_date
        else:
            return None

    def save(self, *args, **kwargs):
        self.borrow_times_db = self.borrow_times()
        self.is_all_return_db = self.is_all_return()
        super().save(*args, **kwargs)

    # for s in Student.objects.all():
    # ...     s.save()
    #刚加入时有小bug，用该语句“刷新”2023.7.11



class BookCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def book_quantity(self):
        return Book.objects.filter(
            category=self,
            pub_date__lte=timezone.now()
        ).aggregate(models.Sum('total_quantity'))['total_quantity__sum']

    def book_count(self):
        return Book.objects.filter(
            category=self,
            pub_date__lte=timezone.now()
        ).count()


class Book(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField('data published')
    total_quantity = models.IntegerField(default=1, null=False)
    offered_by = models.ForeignKey(School, on_delete=models.PROTECT)
    cover_image = models.ImageField(upload_to='books/cover_images', null=True, blank=True)
    category = models.ForeignKey(BookCategory, on_delete=models.PROTECT)
    borrow_times_db = models.IntegerField(default=0)  # 冗余优化

    def __str__(self):
        return f"{self.id}-{self.name}"

    def latest_borrow_date(self):
        latest_borrow_record =  BorrowRecord.objects.filter(
            book=self,
            borrow_date__lte=timezone.now()
        ).order_by('-borrow_date').first()
        if latest_borrow_record:
            return latest_borrow_record.borrow_date
        else:
            return None

    def was_borrowed_recently(self):
        one_day_ago = timezone.now() - datetime.timedelta(days=1)
        recent_borrow_records = BorrowRecord.objects.filter(
            book=self,
            borrow_date__gte=one_day_ago,
            borrow_date__lte=timezone.now()
        )

        return recent_borrow_records.exists()

    @property
    def available_quantity(self):
        borrow_records = BorrowRecord.objects.filter(
            book=self,
            borrow_date__lte=timezone.now()
        )
        return_records = ReturnRecord.objects.filter(
            borrowrecord__in=borrow_records,
            return_date__lte=timezone.now()
        )
        return self.total_quantity - borrow_records.count() + return_records.count()

    def borrow_times(self):
        return BorrowRecord.objects.filter(
            book=self,
            borrow_date__lte=timezone.now()
        ).count()

    def save(self, *args, **kwargs):
        self.borrow_times_db = self.borrow_times()
        super().save(*args, **kwargs)



class BorrowRecord(models.Model):
    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    borrow_date = models.DateTimeField()
    isreturned = models.BooleanField(default=False)  # 逻辑优化（修正）

    # def isreturn(self):
    #     return ReturnRecord.objects.exists(
    #         return_date__lte=timezone.now(),
    #         borrowrecord = self
    #     )
    # 循环依赖
    def __str__(self):
        return f"borrow：{self.student.name} - {self.book.name}"

    def save(self, *args, **kwargs):
        if self.book.available_quantity <= 0:
            raise ValueError('The available quantity of this book is 0，no borrow allowed now')
        super().save(*args,**kwargs)
        self.book.save()
        self.student.save()

    def delete(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.book.save()
        self.student.save()


    # def save(self, *args, **kwargs):
    #     self.book.borrow_times += 1
    #     self.book.save()
    #     super().save(*args, **kwargs)
    #
    # def delete(self, *args, **kwargs):
    #     self.book.borrow_times -= 1
    #     self.book.save()
    #     super().delete(*args, **kwargs)
    #  这个逻辑无法成立，因为bookrecord不仅仅在创建时会使用save方法


class ReturnRecord(models.Model):
    return_date = models.DateTimeField()
    borrowrecord = models.ForeignKey(BorrowRecord, on_delete=models.CASCADE)

    def __str__(self):
        return f"return:{self.borrowrecord.student.name}-{self.borrowrecord.book.name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.borrowrecord.isreturned = True
        self.borrowrecord.save()
        # 该逻辑是可以成立的

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.borrowrecord.isreturned = False
        self.borrowrecord.save()

templates/books/detail/book_detail.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Do Your Book Management
{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-4">
        <div class="card-body">
        <div class="row mb-2 fw-bold border-bottom">
            <div class="col-1">ID</div>
            <div class="col-5">Name</div>
            <div class="col-2">Category</div>
            <div class="col-2">School provided</div>
            <div class="col-1">B.Times</div>
            <div class="col-1">Quantity</div>
        </div>
        <div class="row font-monospace small">
            <div class="col-1">{{ book.id }}</div>
            <div class="col-5">{{ book.name }}</div>
            <div class="col-2">{{ book.category }}</div>
            <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis">{{ book.offered_by }}</div>
            <div class="col-1">{{ book.borrow_times_db }}</div>
            <div class="col-1">{{ book.available_quantity|stringformat:"02d" }}/{{ book.total_quantity|stringformat:"02d" }}</div>
        </div>
        </div>
    </div>

    <form method="get" class="mx-2">
        <div class="row">
        <div class="col-auto">
            <div class="mt-3 d-flex align-items-center">
                <label for="stu_Input" class="me-3 col-auto">Enter student ID or name</label>
                <input id="stu_Input" type="text" name="stu_inf" class="form-control" placeholder="Student ID" required value="{{ stu_inf}}">
{#                Django内置没有补全功能，因此只能硬输入#}
            </div>
        </div>
        <div class="col-auto"><button type="submit" class="btn btn-outline-secondary mt-3">Confirm</button></div>
        </div>
    </form>

    {% if not student and stu_inf%}
    <div class="justify-content-start alert alert-secondary" role="alert">
        There is no student with this ID in the database. Please register first.
    </div>
    {% elif student %}
        <div class="card">
        <div class="card-header bg-secondary text-white">
            <h5>Please choose to borrow or return this book.</h5>
        </div>
        <div class="card-body">
        <form action="{% url 'books:book_run' book.id student.stu_id %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-auto">
            <input class="form-check-input" type="radio" name="b_or_r" id="b" value=1 {% if not book.available_quantity %}disabled{% endif %}>
            <label class="form-check-label fw-bold" for="b">Borrow
                {% if not book.available_quantity %}
                    <div class="alert alert-secondary" role="alert">
                        This book is currently checked out and not available for borrowing.
                    </div>
                {% endif %}
            </label>
            <br>
            <input type="radio" class="form-check-input" name="b_or_r" id="r" value=2 {% if not can_return %}disabled{% endif %}>
            <label class="form-check-label fw-bold" for="r">Return
                {% if not can_return %}
                    <div class="alert alert-secondary" role="alert">
                        This student does not have a borrow record for this book and cannot return it.
                    </div>
                {% endif %}
            </label>
            </div>
            <div class="col-auto">
            <button type="submit" class="btn btn-outline-secondary" {% if not can_return and not book.available_quantity %}disabled{% endif %}>Submit</button>
            </div>
        </div>
        </form>
        </div>
        </div>

    {% endif %}



</div>

{% endblock content %}

templates/books/detail/category_detail.html
{% extends "books/base_file/base.html" %}

{#这里的列表其实也可以引用book.index的模版，但是就是想多写#}

{% block subtitle %}
    Tap and Request
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    {{ category.name}} Books
                </h4>
            </div>

            <div class="card-body">
                {% if category.book_set.all %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-1">ID</div>
                        <div class="col-5">Name</div>
                        <div class="col-5">Provided School</div>
                    </div>
                    {% for book in category.book_set.all %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-1">{{ book.id }}</div>
                        <div class="col-5"><a href="{% url 'books:book_detail' book.id %}" class="text-decoration-none text-black"> {{ book.name }}</a></div>
                        <div class="col-5"><a href="{% url 'books:school_detail' book.offered_by.id %}" class="text-decoration-none text-black">{{ book.offered_by.name }}</a></div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text"> No Books are available.</p>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

templates/books/detail/major_detail.html
{% extends "books/base_file/base.html" %}

{#这里的列表其实也可以引用student.index的模版，但是就是想多写#}

{% block subtitle %}
    Tap and Request
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    Students Major in {{ major.name }}
                </h4>
            </div>

            <div class="card-body">
                {% if major.student_set.all %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-1">ID</div>
                        <div class="col-3">Name</div>
                        <div class="col-1">Sex</div>
                        <div class="col-1">Grade</div>
                        <div class="col-5">School</div>
                    </div>
                    {% for student in major.student_set.all %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-1">{{ student.stu_id }}</div>
                        <div class="col-3"><a href="{% url 'books:student_detail' student.id %}" class="text-decoration-none text-black"> {{ student.name }}</a></div>
                        <div class="col-1">{{ student.sex }}</div>
                        <div class="col-1">{{ student.grade }}</div>
                        <div class="col-5"><a href="{% url 'books:school_detail' student.school.id %}" class="text-decoration-none text-black">{{ student.school }}</a></div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text"> No Students are available.</p>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

templates/books/detail/school_detail.html
{% extends "books/base_file/base.html" %}
{#这里的列表其实也可以引用student.index、book.index的模版，但是就是想多写#}
{% block subtitle %}
    Tap and Request
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    Students from {{ school.name }}
                </h4>
            </div>

            <div class="card-body" style="height:450px;overflow-y: scroll;">
                {% if school.student_set.all %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-2">ID</div>
                        <div class="col-3">Name</div>
                        <div class="col-1">Sex</div>
                        <div class="col-1">Grade</div>
                        <div class="col-3">Major</div>
                    </div>
                    {% for student in school.student_set.all %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-2">{{ student.stu_id }}</div>
                        <div class="col-3"><a href="{% url 'books:student_detail' student.id %}" class="text-decoration-none text-black"> {{ student.name }}</a></div>
                        <div class="col-1">{{ student.sex }}</div>
                        <div class="col-1">{{ student.grade }}</div>
                        <div class="col-3"><a href="{% url 'books:major_detail' student.major.id %}" class="text-decoration-none text-black">{{ student.major }}</a></div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text"> No Student are available.</p>
                {% endif %}
            </div>

        </div>
    </div>

    <div class="container">
        <div class="card mt-4">
            <div class="card-header bg-secondary text-white">
                <h4>
                    Books provided by {{ school.name }}
                </h4>
            </div>

            <div class="card-body" style="height:450px;overflow-y: scroll;">
                {% if school.book_set.all %}
                    <div class="row mb-2 fw-bold border-bottom">
                        <div class="col-2">ID</div>
                        <div class="col-5">Name</div>
                        <div class="col-3">Category</div>
                        <div class="col-1">Quantity</div>
                    </div>
                    {% for book in school.book_set.all %}
                    <div class="row font-monospace mb-2 small">
                        <div class="col-2">{{ book.id }}</div>
                        <div class="col-5"><a href="{% url 'books:book_detail' book.id %}" class="text-decoration-none text-black"> {{ book.name }}</a></div>
                        <div class="col-3"><a href="{% url 'books:category_detail' book.category.id %}" class="text-black text-decoration-none"> {{ book.category }}</a></div>
                        <div class="col-1">{{ book.available_quantity|stringformat:"02d" }}/{{ book.total_quantity|stringformat:"02d" }}</div>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="card-text">No Student are available.</p>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content %}

templates/books/detail/student_detail.html
{% extends "books/base_file/base.html" %}

{% block subtitle %}
    Do Your Book Management
{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-4">
        <div class="card-body">
        <div class="row mb-2 fw-bold border-bottom">
            <div class="col-1">Stu_ID</div>
            <div class="col-2">Name</div>
            <div class="col-1">Sex</div>
            <div class="col-2">School</div>
            <div class="col-2">Major</div>
            <div class="col-1">Grade</div>
            <div class="col-1">B. Times</div>
            <div class="col-1">Latest B.</div>
            <div class="col-1">Latest R.</div>
        </div>
        <div class="row font-monospace">
            <div class="col-1"><a href="{% url 'books:student_detail' student.id %}">{{ student.stu_id }}</a></div>
            <div class="col-2">{{ student.name }}</div>
            <div class="col-1">{{ student.sex }}</div>
            <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis">{{ student.school.name }}</div>
            <div class="col-2" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis">{{ student.major }}</div>
            <div class="col-1">{{ student.grade }}</div>
            <div class="col-1">{{ student.borrow_times}}</div>
            <div class="col-1">{{ student.latest_borrow_date|date:"y-m-d"|default:"None"}}</div>
            <div class="col-1">{{ student.latest_return_date|date:"y-m-d"|default:"None"}}</div>
            </div>
        </div>
    </div>

{% if not student.is_all_return_db %}
    <div class="card mt-4">
        <div class="card-header bg-secondary text-white">
            <h6>List of Unreturned Records</h6>
        </div>
        <div class="card-body">
            <div class="row mb-2 fw-bold border-bottom">
                <div class="col-1">Book ID</div>
                <div class="col-5">Book Name</div>
                <div class="col-2">Borrow Time</div>
            </div>
            {% for timeout_record in timeout_records %}
            <div class="row mb-2 fw-bold border-bottom text-warning">
                <div class="col-1">{{ timeout_record.book.id }}</div>
                <div class="col-5">{{ timeout_record.book.name}}</div>
                <div class="col-2">{{ timeout_record.borrow_date}}</div>
            </div>
            {% endfor %}
            {% for notreturn_record in notreturn_records %}
            {% if notreturn_record not in timeout_records %}
             <div class="row mb-2 fw-bold border-bottom">
                <div class="col-1">{{ notreturn_record.book.id }}</div>
                <div class="col-5">{{ notreturn_record.book.name}}</div>
                <div class="col-2">{{ notreturn_record.borrow_date|date:"y-m-d"}}</div>
                <div class="col-auto">
                    <form action="{% url 'books:student_run' notreturn_record.book.id student.stu_id  %}" method="post">
                    {% csrf_token %}
                        <input type="hidden" name="b_or_r" value="2">
                        <button type="submit" class="btn btn-outline-secondary small">return</button>
                    </form>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endif %}

<form method="get" class="mx-2">
    <div class="row">
    <div class="col-auto">
        <div class="mt-3 d-flex align-items-center">
            <label for="book_inf" class="me-3 col-auto">Enter Book ID or name</label>
            <input id="book_inf" type="text" name="book_inf" class="form-control" placeholder="Book ID" required value="{{ book_inf}}">
        </div>
    </div>
    <div class="col-auto"><button type="submit" class="btn btn-outline-secondary mt-3">Confirm</button></div>
    </div>
</form>

{% if not book and book_inf %}
    <div class="justify-content-start alert alert-secondary" role="alert">
        There is no Book with this ID in the database. Please change an input
    </div>
{% elif book%}
    <div class="card">
    <div class="card-header bg-secondary text-white">
        <h5>Please check the book you chose.</h5>
    </div>
    <div class="card-body">
    <form action="{% url 'books:student_run' book.id student.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="b_or_r" value="1">
    <div class="row"><div class="col-auto">id:{{ book.id }}《{{ book.name }}》</div></div>
    <div class="row"><div class="col-auto">
        <button type="submit" class="btn btn-outline-secondary" {% if not book.available_quantity %}disabled{% endif %}>Borrow</button>
        </div></div>
    </form>
    </div>
{% endif %}


</div>
{% endblock content %}